services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.ponces.xyz`)"
      - "traefik.http.routers.filebrowser.entrypoints=web"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    volumes:
      - ./files:/srv
      - ./filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=1000
      - PGID=1000

networks:
  web:
    external: true
