services:
  registry:
    image: registry:3
    container_name: registry
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.apps.ponces.dev`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.tls.certresolver=cloudflare"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data:

networks:
  web:
    external: true
