services:
  gitea:
    image: docker.gitea.com/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.apps.ponces.dev`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`gitea.apps.ponces.dev`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=2222"
    volumes:
      - gitea-config:/etc/gitea
      - gitea-data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true

volumes:
  gitea-config:
  gitea-data:

networks:
  web:
    external: true
