services:
  ponces-gsi-runner:
    image: ponces/github-runner
    container_name: ponces-gsi-runner
    restart: always
    privileged: true
    build:
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
        S6_OVERLAY_VERSION: ${S6_OVERLAY_VERSION}
    env_file:
      - ponces.env

  aosp-gsi-runner:
    image: ponces/github-runner
    container_name: aosp-gsi-runner
    restart: always
    privileged: true
    build:
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
        S6_OVERLAY_VERSION: ${S6_OVERLAY_VERSION}
    env_file:
      - aosp.env
