services:
  ponces-gsi-runner:
    image: ponces/github-runner
    container_name: ponces-gsi-runner
    restart: unless-stopped
    build:
      target: dood-runner
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
        S6_OVERLAY_VERSION: ${S6_OVERLAY_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ponces.env

  aosp-gsi-runner:
    image: ponces/github-runner
    container_name: aosp-gsi-runner
    restart: unless-stopped
    build:
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
        S6_OVERLAY_VERSION: ${S6_OVERLAY_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - aosp.env
