services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`vpn.apps.ponces.xyz`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.routers.wg-easy.tls=true"
      - "traefik.http.routers.wg-easy.tls.certresolver=cloudflare"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"
    volumes:
      - etc_wireguard:/etc/wireguard
    environment:
      - WG_HOST=vpn.apps.ponces.xyz
      - PASSWORD_HASH=${WG_EASY_PASSWORD}
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  etc_wireguard:

networks:
  web:
    external: true
